#!/bin/bash

JMDNS_DIR=`rospack find zeroconf_jmdns`
JMDNS_JAR=${JMDNS_DIR}/build/javax.jmdns-3.4.1.jar
DEMOS_DIR=`rospack find zeroconf_jmdns_demos`
DEMOS_JAR=${DEMOS_DIR}/build/javax.jmdns.demos-0.0.1.jar
OUR_CLASSPATH=${JMDNS_JAR}:${DEMOS_JAR}

# java -classpath ${OUR_CLASSPATH} javax.jmdns.demos.RegisterServices

# Just run the default code (if created by ant's jar with Main-Class attribute
java -jar ${DEMOS_JAR} --discover_services

# This fails because it the executing main has to be cast from a NodeMain type.
#rosrun rosjava_bootstrap run.py jmdns_demos javax.jmdns.demos.RegisterServices

# This one works fine whether we use the ant bundle or the ant jar
# rosrun yujin_java_tools run.py jmdns_demos javax.jmdns.demos.RegisterServices

